const $ = (s) => document.querySelector(s);
const state = { page: 'overview', summary: null, categories: [], logs: [], platform: 'Linux', category: 'authentication_session', clients: [] };
const api = async (path, options = {}) => { const r = await fetch(path, options); if (!r.ok) throw new Error(`请求失败 ${r.status}`); const body = await r.json(); return body.data ?? body; };
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message) { $('#toast').innerHTML = `<div class="toast-msg">${esc(message)}</div>`; setTimeout(() => $('#toast').innerHTML = '', 2600); }
function clock() { $('#clock').textContent = new Date().toLocaleString('zh-CN', {hour12:false}); } setInterval(clock, 1000); clock();
function shell(title, desc, actions='') { return `<div class="page-title"><div><h1>${title}</h1><p>${desc}</p></div><div>${actions}</div></div>`; }
function metric(label, value, hint, icon) { return `<div class="metric"><span class="metric-icon">${icon}</span><div class="label">${label}</div><div class="number">${value}</div><div class="hint">${hint}</div></div>`; }

async function renderOverview() {
  $('#main').innerHTML = shell('运行概览', '平台日志接收与审计运行状态') + `<div class="cards" id="overview-cards"></div><div class="grid-2"><section class="panel"><div class="panel-head"><h2>日志类别分布</h2><button class="btn" onclick="navigate('logs')">进入日志管理 →</button></div><div id="category-list" class="category-list"></div></section><section class="panel"><div class="panel-head"><h2>系统状态</h2><span class="tag green">运行正常</span></div><div class="category"><span>Linux 数据库</span><b class="tag green">已连接</b></div><div class="category"><span>Windows 数据库</span><b class="tag green">已连接</b></div><div class="category"><span>SSE 实时通道</span><b class="tag green">可用</b></div><div class="bar"><span style="width:100%"></span></div></section></div>`;
  try { state.summary = await api('/api/v1/logs/summary'); const s = state.summary; $('#overview-cards').innerHTML = metric('日志总量', s.total.toLocaleString(), '实时统计', '▤') + metric('Linux 日志', s.by_platform.Linux.toLocaleString(), '审计日志', '◈') + metric('Windows 日志', s.by_platform.Windows.toLocaleString(), '事件日志', '▦') + metric('数据库状态', '正常', '双库在线', '✓'); $('#category-list').innerHTML = s.categories.map(x => `<div class="category"><span><small>${x.platform}</small><br>${x.label}</span><b>${x.count.toLocaleString()}</b></div>`).join(''); } catch (e) { toast(e.message); }
}

async function renderHeartbeat() {
  $('#main').innerHTML = shell('客户端心跳监控', '持续查看采集客户端在线状态、心跳延迟和日志产出', '<button class="btn" onclick="loadHeartbeat()">↻ 刷新</button>') + `<div class="cards" id="heartbeat-cards"></div><section class="panel"><div class="panel-head"><h2>客户端列表</h2><button class="btn" onclick="exportClients()">导出 CSV</button></div><div class="filters"><input id="client-keyword" class="input" placeholder="搜索客户端 / IP"><select id="client-os" class="select"><option value="">全部系统</option><option>Linux</option><option>Windows</option></select><button class="btn primary" onclick="loadHeartbeat()">查询</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>客户端</th><th>地址</th><th>系统</th><th>最近心跳</th><th>延迟</th><th>状态</th><th>操作</th></tr></thead><tbody id="client-rows"></tbody></table></div></section>`; await loadHeartbeat(); }
async function loadHeartbeat() { try { const s = await api('/api/v1/monitor/summary'); const keyword = encodeURIComponent($('#client-keyword')?.value || ''); const os = encodeURIComponent($('#client-os')?.value || ''); const d = await api(`/api/v1/monitor/clients?keyword=${keyword}&os_type=${os}`); state.clients = d.items || []; $('#heartbeat-cards').innerHTML = metric('客户端总数', s.total, '纳管客户端', '◉') + metric('在线客户端', s.states.ONLINE, `${s.onlineRate}% 在线率`, '✓') + metric('延迟客户端', s.states.DELAYED, '需要关注', '◌') + metric('离线客户端', s.states.OFFLINE, '连接中断', '×'); $('#client-rows').innerHTML = state.clients.length ? state.clients.map(c => `<tr><td><b>${esc(c.clientId)}</b><br><small>${esc(c.serverName)}</small></td><td>${esc(c.ipAddress || '-')}</td><td>${esc(c.os_type)}</td><td>${esc(c.lastHeartbeatAt)}</td><td>${c.heartbeatDelaySec}s</td><td><span class="tag ${c.heartbeatStatus==='ONLINE'?'green':c.heartbeatStatus==='DELAYED'?'orange':'red'}">${c.heartbeatStatus}</span></td><td><button class="btn" onclick="showClient('${encodeURIComponent(c.clientId)}')">详情</button></td></tr>`).join('') : `<tr><td colspan="7" class="empty">暂无心跳数据。等待采集客户端上报。</td></tr>`; } catch (e) { toast(e.message); } }
function exportClients() { const rows = [['clientId','serverName','ipAddress','os','status'], ...state.clients.map(c => [c.clientId,c.serverName,c.ipAddress,c.os_type,c.heartbeatStatus])]; downloadCsv('clients.csv', rows); }
async function showClient(id) { const c = state.clients.find(x => x.clientId === decodeURIComponent(id)); if (!c) return; $('#toast').innerHTML = `<div class="modal-backdrop" onclick="this.remove()"><div class="modal" onclick="event.stopPropagation()"><button class="modal-close" onclick="this.closest('.modal-backdrop').remove()">×</button><h2>客户端详情</h2><div class="detail-grid">${Object.entries(c).filter(([k])=>k!=='received_at').map(([k,v])=>`<div><small>${k}</small>${esc(v)}</div>`).join('')}</div><h3>最近日志</h3><p class="muted">日志详情将根据客户端标识和统一索引继续细化。</p></div></div>`; }

async function renderLogs() { $('#main').innerHTML = shell('融合日志管理', '按平台、日志类别和关键词检索融合日志', '<button class="btn" onclick="loadLogs()">↻ 刷新</button>') + `<div class="cards" id="log-cards"></div><section class="panel"><div class="panel-head"><h2>日志查询</h2><button class="btn" onclick="exportLogs()">导出当前结果</button></div><div class="filters"><select id="platform" class="select" onchange="changePlatform()"><option>Linux</option><option>Windows</option></select><select id="category" class="select"></select><input id="log-keyword" class="input" placeholder="主机、IP、类型关键词"><button class="btn primary" onclick="loadLogs()">查询</button></div><div class="table-wrap"><table class="data-table"><thead id="log-head"></thead><tbody id="log-rows"></tbody></table></div></section>`; try { state.categories = await api('/api/v1/logs/categories'); changePlatform(); await loadLogs(); connectSse(); } catch (e) { toast(e.message); } }
function changePlatform() { state.platform = $('#platform').value; const list = state.categories.filter(x => x.platform === state.platform); $('#category').innerHTML = list.map(x => `<option value="${x.key}">${x.label}</option>`).join(''); state.category = $('#category').value; }
async function loadLogs() { try { state.platform = $('#platform').value; state.category = $('#category').value; const key = encodeURIComponent($('#log-keyword')?.value || ''); const d = await api(`/api/v1/logs/categories/${state.category}?platform=${state.platform}&page=1&size=20&keyword=${key}`); state.logs = d.items || []; $('#log-cards').innerHTML = metric('查询结果', d.total.toLocaleString(), `${state.platform} · ${state.category}`, '▤') + metric('当前页', state.logs.length, '20 条/页', '▦') + metric('接收状态', '接收中', 'SSE 已连接', '●') + metric('当前平台', state.platform, '动态类别', '◇'); if (!state.logs.length) { $('#log-head').innerHTML=''; $('#log-rows').innerHTML='<tr><td class="empty">暂无匹配日志</td></tr>'; return; } const keys = Object.keys(state.logs[0]); $('#log-head').innerHTML = '<tr>' + keys.map(k=>`<th>${esc(k)}</th>`).join('') + '<th>操作</th></tr>'; $('#log-rows').innerHTML = state.logs.map((row,i)=>`<tr>${keys.map(k=>`<td>${esc(row[k])}</td>`).join('')}<td><button class="btn" onclick="showLog(${i})">详情</button></td></tr>`).join(''); } catch(e) { toast(e.message); } }
function showLog(i) { const row = state.logs[i]; $('#toast').innerHTML = `<div class="modal-backdrop" onclick="this.remove()"><div class="modal" onclick="event.stopPropagation()"><button class="modal-close" onclick="this.closest('.modal-backdrop').remove()">×</button><h2>日志详情</h2><div class="detail-grid">${Object.entries(row).map(([k,v])=>`<div><small>${esc(k)}</small>${esc(v)}</div>`).join('')}</div></div></div>`; }
function exportLogs() { const keys = state.logs.length ? Object.keys(state.logs[0]) : []; downloadCsv(`${state.category}.csv`, [keys, ...state.logs.map(r=>keys.map(k=>r[k]))]); }
function connectSse() { if (window._sse) window._sse.close(); window._sse = new EventSource('/api/v1/logs/stream'); window._sse.addEventListener('log', e => { const item = JSON.parse(e.data); toast(`收到新的 ${item.category || '日志'}`); }); }

async function renderEvidence() { $('#main').innerHTML = shell('日志完整性存证', '验证原始日志内容未被篡改', '<button class="btn" onclick="renderEvidence()">↻ 刷新</button>') + `<div class="cards" id="evidence-cards"></div><section class="panel"><div class="panel-head"><h2>存证记录</h2><button class="btn" onclick="location.href='/api/v1/evidence/export'">导出存证</button></div><div class="filters"><select id="evidence-status" class="select"><option value="">全部状态</option><option>VALID</option><option>HASH_MISMATCH</option><option>RAW_MISSING</option><option>PENDING</option></select><button class="btn primary" onclick="loadEvidence()">查询</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>存证 ID</th><th>接收时间</th><th>日志类别</th><th>SHA-256</th><th>校验状态</th></tr></thead><tbody id="evidence-rows"></tbody></table></div></section>`; await loadEvidence(); }
async function loadEvidence() { try { const s = await api('/api/v1/evidence/summary'); const d = await api(`/api/v1/evidence?page=1&size=100&status=${encodeURIComponent($('#evidence-status')?.value || '')}`); $('#evidence-cards').innerHTML = metric('存证总数', s.total, '独立原始记录', '▣') + metric('校验正常', s.statuses.VALID, 'SHA-256 一致', '✓') + metric('哈希异常', s.statuses.HASH_MISMATCH, '需要复核', '△') + metric('待校验', s.statuses.PENDING, '等待校验', '◌'); $('#evidence-rows').innerHTML = d.items?.length ? d.items.map(x=>`<tr><td>${esc(x.evidence_id)}</td><td>${esc(x.received_at)}</td><td>${esc(x.category)}</td><td>${esc(x.raw_hash)}</td><td><span class="tag ${x.verify_status==='VALID'?'green':x.verify_status==='PENDING'?'orange':'red'}">${esc(x.verify_status)}</span></td></tr>`).join('') : '<tr><td colspan="5" class="empty">当前数据库尚未产生存证记录</td></tr>'; } catch(e) { toast(e.message); } }
function downloadCsv(name, rows) { const text = rows.map(r => r.map(v => `"${String(v ?? '').replaceAll('"','""')}"`).join(',')).join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['\ufeff'+text], {type:'text/csv'})); a.download = name; a.click(); }
function navigate(page) { state.page = page; document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active', x.dataset.page===page)); ({overview:renderOverview,heartbeat:renderHeartbeat,logs:renderLogs,evidence:renderEvidence}[page] || renderOverview)(); }
document.querySelectorAll('.nav-item[data-page]').forEach(x => x.addEventListener('click', () => navigate(x.dataset.page))); navigate('overview');
